In [1]:
import numpy as np

In [4]:
input_value = np.array([[0,0],[0,1],[1,1],[1,0]])
input_value.shape
input_value


array([[0, 0],
       [0, 1],
       [1, 1],
       [1, 0]])

In [5]:
ouput_value = np.array([0,1,1,0])
ouput_value.reshape(4,1)
ouput_value

array([0, 1, 1, 0])

In [6]:
weights=np.array([[0.1],[0.2]])

In [7]:
bies = 0.3

In [9]:
def sigmoid_function(x):
    return 1/(1+np.exp(-x))

In [11]:
def derivation_sigmoid(x):
    return sigmoid_function(x)*(1-sigmoid_function(x))

In [12]:
for epochs in range(10000):
    input_array = input_value
    
    weigted_sum = np.dot(input_array,weights)+bies
    first_output = sigmoid_function(weigted_sum)
    
    error = first_output-ouput_value
    total_error = np.square(np.subtract(first_output,ouput_value)).mean()
    
    first_der = error
    seccond_der = derivation_sigmoid(first_output)
    derivation = first_der*seccond_der
    
    t_input = input_value.T
    final_derivation = np.dot(t_input,derivation)
    
    weights = weights-0.5*final_derivation
    
    for i in derivation:
        bies = bies-0.5*i
        
print(weights)
print(bies)

[[-1.92140234  1.85269664  1.85269664 -1.92140234]
 [-1.89198324  1.88371476  1.88371476 -1.89198324]]
[-7.44917034  7.2234464   7.2234464  -7.44917034]


In [13]:
predict = np.array([0,1])
result = np.dot(predict,weights)+bies
res = sigmoid_function(result)
print(res)

[8.77304669e-05 9.99889143e-01 9.99889143e-01 8.77304669e-05]
