In [1]:
import cv2
from numpy import genfromtxt

In [2]:
data  = genfromtxt('data/bank_note_data.txt',delimiter=',')

In [3]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [4]:
label = data[:,4]

In [5]:
label

array([0., 0., 0., ..., 1., 1., 1.])

In [6]:
features = data[:,0:4]

In [7]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [8]:
X = features

In [9]:
y=label

In [10]:
from sklearn.model_selection import train_test_split 

In [11]:
 X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [12]:
len(X)

1372

In [13]:
len(X_train)

919

In [14]:
len(X_test)

453

In [15]:
len(y)

1372

In [16]:
len(y_train)

919

In [17]:
from sklearn.preprocessing import MinMaxScaler

In [18]:
scaler_object = MinMaxScaler()

In [19]:
scaler_object.fit(X_train)

MinMaxScaler()

In [20]:
scaled_X_train = scaler_object.transform(X_train)

In [21]:
scaled_X_test = scaler_object.transform(X_test)

In [22]:

from keras.models import Sequential
from keras.layers import Dense

In [23]:
model = Sequential()


In [24]:
model.add(Dense(4,input_dim=4,activation='relu'))

In [25]:
model.add(Dense(8,activation='relu'))

In [26]:
model.add(Dense(1,activation='sigmoid'))

In [27]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [28]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
29/29 - 1s - loss: 0.7101 - accuracy: 0.4940 - 985ms/epoch - 34ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6838 - accuracy: 0.5582 - 60ms/epoch - 2ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6707 - accuracy: 0.5952 - 65ms/epoch - 2ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6618 - accuracy: 0.6355 - 60ms/epoch - 2ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6537 - accuracy: 0.6627 - 65ms/epoch - 2ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6397 - accuracy: 0.6866 - 65ms/epoch - 2ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6238 - accuracy: 0.7149 - 75ms/epoch - 3ms/step
Epoch 8/50
29/29 - 0s - loss: 0.6092 - accuracy: 0.7203 - 70ms/epoch - 2ms/step
Epoch 9/50
29/29 - 0s - loss: 0.5942 - accuracy: 0.7345 - 75ms/epoch - 3ms/step
Epoch 10/50
29/29 - 0s - loss: 0.5787 - accuracy: 0.7421 - 70ms/epoch - 2ms/step
Epoch 11/50
29/29 - 0s - loss: 0.5627 - accuracy: 0.7541 - 80ms/epoch - 3ms/step
Epoch 12/50
29/29 - 0s - loss: 0.5468 - accuracy: 0.7552 - 75ms/epoch - 3ms/step
Epoch 13/50
29/29 - 0s - loss: 0.53

In [29]:
model.metrics_names

['loss', 'accuracy']

In [30]:
from sklearn.metrics import confusion_matrix,classification_report

In [31]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 5ms/step


In [32]:
confusion_matrix(y_test,predictions)

array([[253,   4],
       [ 17, 179]], dtype=int64)

In [33]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.94      0.98      0.96       257
         1.0       0.98      0.91      0.94       196

    accuracy                           0.95       453
   macro avg       0.96      0.95      0.95       453
weighted avg       0.95      0.95      0.95       453



In [34]:
model.save('mysupermodel.h5')

In [35]:
from keras.models import load_model

In [36]:
new_model = load_model('mysupermodel.h5')

In [37]:
new_model.predict(scaled_X_test)

15/15 [==============================] - 0s 1ms/step


array([[0.05376136],
       [0.4406313 ],
       [0.27067548],
       [0.07549235],
       [0.04715398],
       [0.0238389 ],
       [0.18786773],
       [0.01006017],
       [0.03792981],
       [0.1235264 ],
       [0.5094376 ],
       [0.8668437 ],
       [0.1560072 ],
       [0.8048832 ],
       [0.5725431 ],
       [0.2733642 ],
       [0.90850335],
       [0.9175049 ],
       [0.8746882 ],
       [0.83646107],
       [0.02597675],
       [0.07549765],
       [0.8539943 ],
       [0.01787888],
       [0.99186766],
       [0.02136901],
       [0.01203659],
       [0.8573159 ],
       [0.00194362],
       [0.00431145],
       [0.74252546],
       [0.10165235],
       [0.15515538],
       [0.99341744],
       [0.9783733 ],
       [0.00975532],
       [0.47910193],
       [0.79112023],
       [0.88440067],
       [0.08716909],
       [0.05462569],
       [0.7377296 ],
       [0.7982396 ],
       [0.03245268],
       [0.9801471 ],
       [0.85803074],
       [0.9462574 ],
       [0.035