In [1]:
import tensorflow as tf

In [3]:
#creating tensor of value 1 of int type
r1=tf.constant (1, tf.int16)  
print (r1)

tf.Tensor(1, shape=(), dtype=int16)


In [6]:
# Named my_scalar  
r2 = tf.constant(1, tf.int16, name = "my_scalar")   
print(r2)  

tf.Tensor(1, shape=(), dtype=int16)


In [8]:
#Decimal data  
q1_decimal = tf.constant(1.12345, tf.float32)  
print(q1_decimal)  
#String data  
q1_string = tf.constant("JavaTpoint", tf.string)  
print(q1_string)

tf.Tensor(1.12345, shape=(), dtype=float32)
tf.Tensor(b'JavaTpoint', shape=(), dtype=string)


In [11]:
q1_vector = tf.constant([1,3,6], tf.int16) 
print(q1_vector)  
q2_boolean = tf.constant([True, True, False], tf.bool)  
print(q2_boolean)  

tf.Tensor([1 3 6], shape=(3,), dtype=int16)
tf.Tensor([ True  True False], shape=(3,), dtype=bool)


In [14]:
q2_matrix = tf.constant([ [1, 2],  
 [3, 4] ],tf.int16)  
print(q2_matrix)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int16)
